services:
  - type: web
    name: wms-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    region: oregon
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: MONGODB_URI
        fromDatabase:
          name: wms-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 90d
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-domain.com,https://your-netlify-app.netlify.app
    healthCheckPath: /api/health
    envKeyAlias: production

databases:
  - name: wms-db
    databaseName: wms
    user: wms_user
    plan: free
